"use client";
/**
 * SummaryPanel Component
 * Tabbed panel: Summary (AI) | Action Items | Notes
 */
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, RefreshCw, ChevronDown, ChevronRight, Plus, CheckSquare } from "lucide-react";
import { cn, getSentimentConfig, formatSeconds } from "@/lib/utils";

import { usePlayerStore } from "@/store";
import { ActionItemCard } from "./ActionItemCard";
import type { Summary, ActionItem, Priority } from "@/types";

interface SummaryPanelProps {
  summary: Summary | null;
  actionItems: ActionItem[];
  onRegenerateSummary: () => Promise<void>;
  onToggleActionItem: (id: string, status: string) => void;
  onUpdateActionItem: (id: string, data: Partial<ActionItem>) => void;
  onDeleteActionItem: (id: string) => void;
  onAddActionItem: (data: { text: string; assignee: string; due_date: string; priority: string }) => void;
  isRegenerating?: boolean;
  meetingId: string;
}

const TABS = ["Summary", "Action Items", "Notes"] as const;
type Tab = typeof TABS[number];

export function SummaryPanel({
  summary, actionItems, onRegenerateSummary, onToggleActionItem,
  onUpdateActionItem, onDeleteActionItem, onAddActionItem, isRegenerating
}: SummaryPanelProps) {
  const [activeTab, setActiveTab] = useState<Tab>("Summary");
  const [showCompleted, setShowCompleted] = useState(false);
  const [showAddForm, setShowAddForm] = useState(false);
  const [newItemText, setNewItemText] = useState("");
  const [newItemAssignee, setNewItemAssignee] = useState("");
  const [newItemDueDate, setNewItemDueDate] = useState("");
  const [newItemPriority, setNewItemPriority] = useState<Priority>("medium");
  const { seekTo } = usePlayerStore();

  const pendingItems = actionItems.filter((a) => a.status !== "done");
  const completedItems = actionItems.filter((a) => a.status === "done");

  const handleAddItem = () => {
    if (!newItemText.trim()) return;
    onAddActionItem({
      text: newItemText,
      assignee: newItemAssignee,
      due_date: newItemDueDate,
      priority: newItemPriority,
    });
    setNewItemText("");
    setNewItemAssignee("");
    setNewItemDueDate("");
    setNewItemPriority("medium");
    setShowAddForm(false);
  };

  const sentimentCfg = summary ? getSentimentConfig(summary.sentiment) : null;

  return (
    <div className="flex flex-col h-full">
      {/* Tab bar */}
      <div className="flex border-b border-white/[0.06] shrink-0 px-4">
        {TABS.map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={cn(
              "px-4 py-3 text-sm font-medium border-b-2 transition-all duration-150",
              activeTab === tab
                ? "border-primary text-primary"
                : "border-transparent text-text-muted-dark hover:text-white"
            )}
          >
            {tab}
            {tab === "Action Items" && actionItems.length > 0 && (
              <span className={cn("ml-1.5 badge text-[10px] px-1.5 py-0 rounded-full",
                pendingItems.length > 0 ? "badge-warning" : "badge-success"
              )}>
                {pendingItems.length || actionItems.length}
              </span>
            )}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <div className="flex-1 overflow-y-auto">
        <AnimatePresence mode="wait">
          {/* ── Summary Tab ─────────────────────────────────────────────── */}
          {activeTab === "Summary" && (
            <motion.div
              key="summary"
              initial={{ opacity: 0, y: 4 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="p-5 space-y-5"
            >
              {/* AI Badge + Regenerate */}
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-1.5">
                  <span className="badge-accent">
                    <Sparkles className="w-3 h-3" />
                    Generated by AI
                  </span>
                  {sentimentCfg && (
                    <span className={cn("badge", sentimentCfg.className)}>
                      {sentimentCfg.emoji} {sentimentCfg.label}
                    </span>
                  )}
                </div>
                <button
                  onClick={onRegenerateSummary}
                  disabled={isRegenerating}
                  className="btn-ghost btn-sm flex items-center gap-1.5 text-text-muted-dark"
                >
                  <RefreshCw className={cn("w-3.5 h-3.5", isRegenerating && "animate-spin")} />
                  {isRegenerating ? "Generating…" : "Regenerate"}
                </button>
              </div>

              {summary ? (
                <>
                  {/* Overview */}
                  {summary.overview && (
                    <div>
                      <h4 className="text-xs font-semibold text-text-muted-dark uppercase tracking-wide mb-2">Overview</h4>
                      <p className="text-sm text-text-muted-dark leading-relaxed">{summary.overview}</p>
                    </div>
                  )}

                  {/* Key Points */}
                  {summary.key_points && summary.key_points.length > 0 && (
                    <div>
                      <h4 className="text-xs font-semibold text-text-muted-dark uppercase tracking-wide mb-2">Key Points</h4>
                      <ul className="space-y-1.5">
                        {summary.key_points.map((point, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm text-text-muted-dark">
                            <span className="w-4 h-4 rounded-full bg-primary/15 text-primary flex items-center justify-center shrink-0 mt-0.5 text-[10px] font-bold">
                              {i + 1}
                            </span>
                            {point}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Chapters */}
                  {summary.chapters && summary.chapters.length > 0 && (
                    <div>
                      <h4 className="text-xs font-semibold text-text-muted-dark uppercase tracking-wide mb-2">Chapters</h4>
                      <div className="space-y-2">
                        {summary.chapters.map((chapter, i) => (
                          <button
                            key={i}
                            onClick={() => seekTo(chapter.start_seconds)}
                            className="w-full text-left p-3 rounded-button bg-white/[0.03] border border-white/[0.06] hover:border-primary/30 hover:bg-primary/[0.04] transition-all group"
                          >
                            <div className="flex items-center gap-2 mb-0.5">
                              <span className="font-mono text-[11px] text-accent">
                                {formatSeconds(chapter.start_seconds)}
                              </span>
                              <span className="text-sm font-medium text-white group-hover:text-primary transition-colors">
                                {chapter.title}
                              </span>
                              <ChevronRight className="w-3.5 h-3.5 text-text-muted-dark ml-auto opacity-0 group-hover:opacity-100 transition-opacity" />
                            </div>
                            <p className="text-xs text-text-muted-dark">{chapter.summary}</p>
                          </button>
                        ))}
                      </div>
                    </div>
                  )}
                </>
              ) : (
                <div className="text-center py-10">
                  <Sparkles className="w-8 h-8 text-primary/40 mx-auto mb-3" />
                  <p className="text-sm text-text-muted-dark mb-4">No summary yet.</p>
                  <button onClick={onRegenerateSummary} className="btn-primary btn-sm">
                    Generate AI Summary
                  </button>
                </div>
              )}
            </motion.div>
          )}

          {/* ── Action Items Tab ─────────────────────────────────────────── */}
          {activeTab === "Action Items" && (
            <motion.div
              key="action-items"
              initial={{ opacity: 0, y: 4 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="p-4"
            >
              {/* Add button */}
              <div className="flex justify-end mb-3">
                <button
                  onClick={() => setShowAddForm(!showAddForm)}
                  className="btn-primary btn-sm"
                >
                  <Plus className="w-3.5 h-3.5" />
                  Add item
                </button>
              </div>

              {/* Add form */}
              <AnimatePresence>
                {showAddForm && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: "auto" }}
                    exit={{ opacity: 0, height: 0 }}
                    className="card p-3 mb-4 space-y-2 overflow-hidden"
                  >
                    <input
                      type="text"
                      value={newItemText}
                      onChange={(e) => setNewItemText(e.target.value)}
                      placeholder="Action item description..."
                      className="input text-sm"
                      onKeyDown={(e) => e.key === "Enter" && handleAddItem()}
                      autoFocus
                    />
                    <div className="flex gap-2">
                      <input
                        type="text"
                        value={newItemAssignee}
                        onChange={(e) => setNewItemAssignee(e.target.value)}
                        placeholder="Assignee"
                        className="input text-sm flex-1"
                      />
                      <input
                        type="date"
                        value={newItemDueDate}
                        onChange={(e) => setNewItemDueDate(e.target.value)}
                        className="input text-sm flex-1"
                      />
                      <select
                        value={newItemPriority}
                        onChange={(e) => setNewItemPriority(e.target.value as Priority)}
                        className="input text-sm w-28"
                      >
                        <option value="low">Low</option>
                        <option value="medium">Medium</option>
                        <option value="high">High</option>
                      </select>
                    </div>
                    <div className="flex gap-2 justify-end">
                      <button onClick={() => setShowAddForm(false)} className="btn-ghost btn-sm">Cancel</button>
                      <button onClick={handleAddItem} className="btn-primary btn-sm">Save</button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Pending items */}
              {pendingItems.length > 0 ? (
                <div className="space-y-0.5">
                  {pendingItems.map((item) => (
                    <ActionItemCard
                      key={item.id}
                      item={item}
                      onToggle={onToggleActionItem}
                      onUpdate={onUpdateActionItem}
                      onDelete={onDeleteActionItem}
                    />
                  ))}
                </div>
              ) : (
                <div className="text-center py-8">
                  <CheckSquare className="w-8 h-8 text-success/40 mx-auto mb-2" />
                  <p className="text-sm text-text-muted-dark">All done! No pending action items.</p>
                </div>
              )}

              {/* Completed items (collapsible) */}
              {completedItems.length > 0 && (
                <div className="mt-4">
                  <button
                    onClick={() => setShowCompleted(!showCompleted)}
                    className="flex items-center gap-2 text-xs text-text-muted-dark hover:text-white transition-colors mb-2"
                  >
                    <ChevronDown className={cn("w-3.5 h-3.5 transition-transform", showCompleted && "rotate-180")} />
                    {completedItems.length} completed
                  </button>
                  <AnimatePresence>
                    {showCompleted && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                        className="space-y-0.5 overflow-hidden"
                      >
                        {completedItems.map((item) => (
                          <ActionItemCard
                            key={item.id}
                            item={item}
                            onToggle={onToggleActionItem}
                            onUpdate={onUpdateActionItem}
                            onDelete={onDeleteActionItem}
                          />
                        ))}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              )}
            </motion.div>
          )}

          {/* ── Notes Tab ──────────────────────────────────────────────── */}
          {activeTab === "Notes" && (
            <motion.div
              key="notes"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex flex-col items-center justify-center py-20 px-8 text-center"
            >
              <div className="w-14 h-14 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center mb-4">
                <span className="text-2xl">📝</span>
              </div>
              <h3 className="text-base font-semibold text-white mb-2">Notes Coming Soon</h3>
              <p className="text-sm text-text-muted-dark">
                Personal notes and annotations will be available in the next release.
              </p>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
